server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Management
          uri: http://localhost:8081
          predicates:
            - Path=/orderMngs/** 
        - id: Recept
          uri: http://localhost:8082
          predicates:
            - Path=/recepts/** 
        - id: Seat
          uri: http://localhost:8083
          predicates:
            - Path=/seats/** 
        - id: ReceptDashBoard
          uri: http://localhost:8084
          predicates:
            - Path= 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Management
          uri: http://Management:8080
          predicates:
            - Path=/orderMngs/** 
        - id: Recept
          uri: http://Recept:8080
          predicates:
            - Path=/recepts/** 
        - id: Seat
          uri: http://Seat:8080
          predicates:
            - Path=/seats/** 
        - id: ReceptDashBoard
          uri: http://ReceptDashBoard:8080
          predicates:
            - Path= 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
