apiVersion: apps/v1
kind: Deployment
metadata:
  name: Seat
  labels:
    app: Seat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Seat
  template:
    metadata:
      labels:
        app: Seat
    spec:
      containers:
        - name: Seat
          image: username/Seat:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5