apiVersion: apps/v1
kind: Deployment
metadata:
  name: Recept
  labels:
    app: Recept
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Recept
  template:
    metadata:
      labels:
        app: Recept
    spec:
      containers:
        - name: Recept
          image: username/Recept:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5